title: "Louis Preonas"
name: "Louis Preonas"
description: "Associate Professor, Agricultural and Resource Economics, University of Maryland"
url: "https://lpreonas.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache

author:
  name: "Louis Preonas"
  bio: "Associate Professor, Department of Agricultural and Resource Economics, University of Maryland"
  email: "lpreonas@umd.edu"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=KcsufWMAAAAJ"

permalink: /:title/

navigation:
  - title: "Home"
    url: /
  - title: "Bio"
    url: /bio/
  - title: "CV"
    url: /files/preonas_cv.pdf
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "Office Hours"
    url: /office-hours/
  - title: "Contact"
    url: /contact/
