title: "Louis Preonas"
name: "Louis Preonas"
description: "Associate Professor, Agricultural and Resource Economics, University of Maryland"
url: "https://lpreonas.github.io"

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Louis Preonas"
  bio: "Associate Professor, Department of Agricultural and Resource Economics, University of Maryland"
  email: "lpreonas@umd.edu"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=KcsufWMAAAAJ"

permalink: /:title/
