title: "Louis Preonas"
name: "Louis Preonas"
description: "Associate Professor, Agricultural and Resource Economics, University of Maryland"
url: "https://www.louispreonas.com"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache

author:
  name: "Louis Preonas"
  bio: "<br>Associate Professor<br><br>Department of Agricultural and Resource Economics<br><br>University of Maryland<br><br>"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=KcsufWMAAAAJ"

permalink: /:title/

masthead:
  sticky: true

after_footer_scripts:
  - /assets/js/active-nav.js

after_footer_scripts:
  - /assets/js/active-nav.js

after_footer_scripts:
  - /assets/js/active-nav.js
  - /assets/js/mobile-sidebar.js
